apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-j3py
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-j3py
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-j3py
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-j3py
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-j3py
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rtcv-tenant/rhtap-demo-app/hacbs-test-project-j3py@sha256:c339e230457e7a6488069a458fcef8f614a6e89525dcac26ecd666d118827233
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
