apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-j3py
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rtcv-tenant/rhtap-demo-app/hacbs-test-project-j3py@sha256:c339e230457e7a6488069a458fcef8f614a6e89525dcac26ecd666d118827233
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
